#!/usr/bin/env node
/**
 * Regenerate `src/stops.ts` from a directory of raw colormap lookup tables.
 *
 * Each input file is `<colormap-id>.js`, ESM-default-exporting a dense table of
 * 8-bit RGB triples sampled at even positions across the colormap:
 *
 *   export default [[215, 249, 208], [214, 248, 206], ...];   // 256 entries
 *
 * Shipping all ~256 entries per colormap would be wasteful: they end up inlined
 * into the GLSL of every image layer (and therefore into the viewer state, the
 * REPORT messages and the URL hash). Instead each table is fitted with a
 * piecewise-linear curve through a subset of its own entries, chosen greedily:
 * start with the two endpoints, then repeatedly promote the entry the current
 * curve reproduces worst, until no entry is off by more than `tolerance` 8-bit
 * levels on any channel. At the default tolerance of 1/255 that keeps the
 * colormaps visually exact while cutting ~256 entries down to ~24.
 *
 * Usage: node tools/generate-stops.mjs <input-dir> [tolerance]
 */

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const OUT = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"src",
	"stops.ts",
);

const inputDir = process.argv[2];
const tolerance = Number(process.argv[3] ?? 1);
if (!inputDir) {
	console.error("usage: node tools/generate-stops.mjs <input-dir> [tolerance]");
	process.exit(1);
}

/** Sample a dense lookup table at `index`, interpolating between neighbours. */
function lerpAt(table, index) {
	const i = Math.min(Math.floor(index), table.length - 2);
	const f = index - i;
	return [0, 1, 2].map(
		(c) => table[i][c] + (table[i + 1][c] - table[i][c]) * f,
	);
}

/**
 * Indices of a minimal-ish subset of `table` whose piecewise-linear
 * interpolation stays within `tolerance` 8-bit levels of every entry.
 */
function fitStops(table, tol) {
	const keep = [0, table.length - 1];
	for (;;) {
		let worstIndex = -1;
		let worstError = 0;
		for (let k = 0; k < keep.length - 1; k++) {
			const [a, b] = [keep[k], keep[k + 1]];
			for (let i = a + 1; i < b; i++) {
				const approx = lerpAt([table[a], table[b]], (i - a) / (b - a));
				const error = Math.max(
					...approx.map((v, c) => Math.abs(v - table[i][c])),
				);
				if (error > worstError) {
					worstError = error;
					worstIndex = i;
				}
			}
		}
		if (worstError <= tol) return keep;
		keep.push(worstIndex);
		keep.sort((x, y) => x - y);
	}
}

const files = readdirSync(inputDir)
	.filter((f) => f.endsWith(".js"))
	.sort();

const entries = [];
for (const file of files) {
	const id = file.slice(0, -".js".length);
	const table = (await import(pathToFileURL(resolve(inputDir, file)))).default;
	const stops = fitStops(table, tolerance).map((i) => {
		const position = Number((i / (table.length - 1)).toFixed(4));
		return `\t\t[${position}, ${table[i].join(", ")}],`;
	});
	entries.push(`\t${id}: [\n${stops.join("\n")}\n\t],`);
	console.log(`${id}: ${table.length} entries → ${stops.length} stops`);
}

writeFileSync(
	OUT,
	`// Generated by tools/generate-stops.mjs — do not edit by hand.
import type { ColormapId } from "@ocean-viewer/protocol";
import type { ColormapStop } from "./types";

/**
 * Piecewise-linear stops per colormap, fitted to the reference 8-bit lookup
 * tables to within ${tolerance}/255 per channel. See the generator for details.
 */
export const COLORMAP_STOPS: Record<ColormapId, readonly ColormapStop[]> = {
${entries.join("\n")}
};
`,
);
console.log(`\nwrote ${OUT}`);
